version: '3.9'

services:
  backend:
    command: >
      sh -c "python manage.py migrate && 
             gunicorn --bind 0.0.0.0:8000 --reload backend.wsgi:application"
  
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./.env