# Generated by Django 5.2.6 on 2025-09-09 13:23

import core.utils.validations
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=64)),
                ('sobrenome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11, validators=[core.utils.validations.CPFValidator], verbose_name='CPF')),
                ('email', models.EmailField(max_length=128, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apelido', models.CharField(max_length=32, verbose_name='Apelido da Loja')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=128, verbose_name='Título')),
                ('imagem', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.CreateModel(
            name='InformacoesEntrega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entrega_estimada', models.DateField()),
                ('rastreador', models.CharField(max_length=32)),
                ('transportadora', models.CharField(max_length=32)),
                ('preco_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço do Frete')),
                ('data_hora_finalizado', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado')),
            ],
            options={
                'verbose_name': 'Informações da Entrega',
                'verbose_name_plural': 'Informações das Entregas',
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=32)),
                ('valor', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
            },
        ),
        migrations.CreateModel(
            name='ContatoDeLoja',
            fields=[
            ],
            options={
                'verbose_name': 'Contato (Loja)',
                'verbose_name_plural': 'Contatos (Lojas)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.contato',),
        ),
        migrations.CreateModel(
            name='ContatoNormal',
            fields=[
            ],
            options={
                'verbose_name': 'Contato (Cliente)',
                'verbose_name_plural': 'Contatos (Clientes)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.contato',),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=64, verbose_name='Nome da Categoria')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='O CEP deve estar no formato XXXXX-XXX.', regex='^\\d{5}-\\d{3}$')])),
                ('logradouro', models.CharField(max_length=128)),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=128, null=True)),
                ('bairro', models.CharField(max_length=128)),
                ('cidade', models.CharField(max_length=32)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default='SP', max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='UF')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loja')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hora_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.CharField(choices=[('A', 'Aguardando Pagamento'), ('R', 'Recusada'), ('E', 'Em Preparo'), ('S', 'Enviada'), ('C', 'Concluída')], default='A', max_length=1)),
                ('id_pagamento_externo', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do Pagamento Externo')),
                ('url_pagamento', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL do Pagamento')),
                ('contato_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contato', verbose_name='Contado do Cliente')),
                ('endereco_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.endereco', verbose_name='Endereço de Entrega')),
                ('info_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.informacoesentrega', verbose_name='Informações de Entrega')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=128)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('qtd_disponivel', models.PositiveIntegerField(default=1, verbose_name='Quantidade Disponível')),
                ('qtd_em_compra', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Compra')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dias_para_disponibilizar', models.PositiveIntegerField(default=0, verbose_name='Dias para Disponibilizar para Entrega')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='DetalheProduto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('propriedade', models.CharField(max_length=64)),
                ('descricao', models.TextField(max_length=128, verbose_name='Descrição')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
            options={
                'verbose_name': 'Detalhe do Produto',
                'verbose_name_plural': 'Detalhes dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='TamanhoProduto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tamanho')),
            ],
            options={
                'verbose_name': 'Tamanho do Produto',
                'verbose_name_plural': 'Tamanhos dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario_congelado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Unitário')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tamanhoproduto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens dos Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ContatoLoja',
            fields=[
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.loja')),
                ('whatsapp', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(13)], verbose_name='WhatsApp')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(13)])),
                ('instagram', models.CharField(max_length=32)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)], verbose_name='CNPJ')),
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.contato', verbose_name='Contato da Loja')),
            ],
            options={
                'verbose_name': 'Contato da Loja',
                'verbose_name_plural': 'Contatos das Lojas',
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['nome'], name='idx_produto_nome'),
        ),
        migrations.AlterUniqueTogether(
            name='imagemproduto',
            unique_together={('imagem', 'produto')},
        ),
        migrations.AlterUniqueTogether(
            name='tamanhoproduto',
            unique_together={('tamanho', 'produto')},
        ),
    ]
