# Generated by Django 5.2.6 on 2025-09-07 12:52

import core.utils.validations
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('sobrenome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11, validators=[core.utils.validations.CPFValidator])),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default='SP', max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('cidade', models.CharField(max_length=32)),
                ('logradouro', models.CharField(max_length=128)),
                ('bairro', models.CharField(max_length=128)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='O CEP deve estar no formato XXXXX-XXX.', regex='^\\d{5}-\\d{3}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('alt_text', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega_estimada', models.DateField()),
                ('rastreador', models.CharField(max_length=32)),
                ('transportadora', models.CharField(max_length=32)),
                ('preco_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_hora_finalizado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('valor', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ContatoLoja',
            fields=[
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.contato')),
                ('whatsapp', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('instagram', models.CharField(max_length=32)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(14)])),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=32)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.endereco')),
                ('contato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contatoloja')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=64)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('C', 'Concluída'), ('P', 'Pendente'), ('A', 'Aguardando Pagamento'), ('R', 'Recusada')], default='A', max_length=1)),
                ('id_pagamento_externo', models.CharField(blank=True, max_length=255, null=True)),
                ('url_pagamento', models.URLField(blank=True, max_length=255, null=True)),
                ('contato_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contato')),
                ('endereco_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.endereco')),
                ('info_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.informacoesentrega')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('descricao', models.TextField()),
                ('qtd_disponivel', models.PositiveIntegerField(default=1)),
                ('qtd_em_compra', models.PositiveIntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario_congelado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalheProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propriedade', models.CharField(max_length=64)),
                ('descricao', models.TextField(max_length=128)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='TamanhoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tamanho')),
            ],
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['nome'], name='idx_produto_nome'),
        ),
        migrations.AlterUniqueTogether(
            name='imagemproduto',
            unique_together={('imagem', 'produto')},
        ),
        migrations.AlterUniqueTogether(
            name='produtocarrinho',
            unique_together={('produto', 'carrinho')},
        ),
        migrations.AlterUniqueTogether(
            name='tamanhoproduto',
            unique_together={('tamanho', 'produto')},
        ),
    ]
